# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Alex', max_length=255),
        ),
    ]
